---
title: "patientProfileR vignette"
author: "Bradley Saul"
date: "June 25, 2015"
output: html_document
---

### Define Variable Map

The package includes a sample dataset `patientsamples`.
```{r}
library(patientProfileR)
library(plyr)
head(patientsamples)
```

```{r, echo = TRUE}
myMap <- aes_map(x = 'start', 
                 xend = 'stop',
                 color = 'drug_1',
                 shape  = 'outcome',
                 vline1 = 'withdrew',
                 vline2 = 'current_status',
                 vline3 = 'major_event')
```

### Define the Baseplot

```{r baseplot, echo = TRUE}
myBaseplot  <- make_baseplot(patientsamples,
                         aes_map = myMap,
                         axis.lim.x    = c(-7,(78*7)+15),
                         axis.breaks.x = c(0, 4*7, 12*7, 29*7, 52*7, 78*7),
                         axis.labels.x = c(0, 4, 12, 29, 52, 78),
                         axis.breaks.y = c(.2, .5, .75, .85),
                         axis.labels.y = c('R', 'P', 'ORCS', 'IVCS')) +
                theme(axis.ticks.y = element_blank())

```

### Make a Patient Plot

```{r patient_plot, echo = TRUE}
allPlots <- dlply(patientsamples, 'id', function(x) {
  plot_patient(myBaseplot, 
               x,
               title = x[1, 'id'],
               aes_map = myMap)
})
allPlots[[5]]
s5 <- subset(patientsamples, id == 'SUBJ5')

plot_patient(myBaseplot, s5, aes_map = myMap)

```

